In [108]:
import pandas as pd
import numpy as np

In [109]:
df = pd.read_pickle("../data/processed/merged_data.pkl")

In [110]:
df

,datetime,open,high,low,close,volume,merge_date,avg_sentiment_polarity,avg_sentiment_neg,avg_sentiment_neu,...,CAPEI,bm,evm,pe_op_basic,pe_op_dil,roa,roe,npm,ps,de_ratio
0,2018-11-30 17:50:00,44.60,44.64,44.55,44.63,179494,2018-11-30,0.998000,0.009000,0.925,...,17.191,0.1,14.855,14.542,14.674,0.216,0.436,0.224,3.194,2.413
1,2018-11-30 17:55:00,44.63,44.63,44.52,44.52,218881,2018-11-30,0.998000,0.009000,0.925,...,17.191,0.1,14.855,14.542,14.674,0.216,0.436,0.224,3.194,2.413
2,2018-11-30 18:00:00,44.52,44.55,44.44,44.49,364114,2018-11-30,0.998000,0.009000,0.925,...,17.191,0.1,14.855,14.542,14.674,0.216,0.436,0.224,3.194,2.413
3,2018-11-30 18:05:00,44.49,44.52,44.44,44.46,251652,2018-11-30,0.998000,0.009000,0.925,...,17.191,0.1,14.855,14.542,14.674,0.216,0.436,0.224,3.194,2.413
4,2018-11-30 18:10:00,44.45,44.51,44.44,44.45,200756,2018-11-30,0.998000,0.009000,0.925,...,17.191,0.1,14.855,14.542,14.674,0.216,0.436,0.224,3.194,2.413
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104023,2024-03-13 22:40:00,171.47,171.65,171.47,171.60,515713,2024-03-13,0.552455,0.027727,0.844,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104024,2024-03-13 22:45:00,171.59,171.71,171.50,171.66,566382,2024-03-13,0.552455,0.027727,0.844,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104025,2024-03-13 22:50:00,171.65,171.65,171.19,171.29,869695,2024-03-13,0.552455,0.027727,0.844,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104026,2024-03-13 22:55:00,171.30,171.30,171.04,171.15,1413942,2024-03-13,0.552455,0.027727,0.844,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104027,2024-03-13 23:00:00,171.14,171.16,171.11,171.12,21317,2024-03-13,0.552455,0.027727,0.844,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [111]:
out = Path("/Users/huangyucheng/Desktop/CIS 5450 project/CIS545_Repo/data/processed/merged_data_check.csv")
df.to_csv(out, index=False)

In [112]:

print(df.columns.tolist())

['datetime', 'open', 'high', 'low', 'close', 'volume', 'merge_date', 'avg_sentiment_polarity', 'avg_sentiment_neg', 'avg_sentiment_neu', 'avg_sentiment_pos', 'daily_news_count', 'CAPEI', 'bm', 'evm', 'pe_op_basic', 'pe_op_dil', 'roa', 'roe', 'npm', 'ps', 'de_ratio']

In [ ]:
# --- News shifted by 1 day ---

# --- Basic: timestamp columns & grouping columns ---
df['datetime']  = pd.to_datetime(df['datetime'], errors='coerce')  # keep timezone-naive
df['merge_date'] = pd.to_datetime(df['merge_date'], errors='coerce').dt.normalize()
df = df.sort_values('datetime')

sa_cols_all = ['avg_sentiment_polarity','avg_sentiment_neg','avg_sentiment_neu',
               'avg_sentiment_pos','daily_news_count']
sa_cols = [c for c in sa_cols_all if c in df.columns]  # safety check in case some columns are missing

# --- News: use aggregated values from “previous trading day” (visibility = T+1) ---
# 1) Daily news table (one row per day)
news_day = (df[['merge_date'] + sa_cols]
            .drop_duplicates('merge_date')
            .dropna(how='all', subset=sa_cols)
            .sort_values('merge_date'))

# 2) First visible day = next calendar day (enforcing “you only see yesterday’s news”)
news_visible = news_day.rename(columns={'merge_date':'visible_from'}).copy()
news_visible['visible_from'] = news_visible['visible_from'] + pd.Timedelta(days=1)

# 3) Trading-day axis
trade_days = (df[['merge_date']].drop_duplicates()
              .sort_values('merge_date')
              .rename(columns={'merge_date':'trade_date'}))

# 4) As-of merge: assign the most recent visible news to each trading day
news_asof = pd.merge_asof(
    trade_days,
    news_visible.rename(columns={'visible_from':'trade_date'}).sort_values('trade_date'),
    on='trade_date',
    direction='backward'
)

# 5) Important: rename columns to *_lag1d before merging back, to avoid name collisions
lag_map = {c: f'{c}_lag1d' for c in sa_cols}
news_asof = news_asof.rename(columns=lag_map)

# 6) Merge back to minute-level data, then forward-fill within the same trading day
#    so that all 5-minute bars on that day get the same lagged sentiment values
df = (df.merge(news_asof, left_on='merge_date', right_on='trade_date', how='left')
        .drop(columns=['trade_date'])
        .sort_values(['merge_date','datetime']))

lag_cols = list(lag_map.values())
if lag_cols:
    df[lag_cols] = df.groupby('merge_date')[lag_cols].ffill()

In [114]:
df

,datetime,open,high,low,close,volume,merge_date,avg_sentiment_polarity,avg_sentiment_neg,avg_sentiment_neu,...,roa,roe,npm,ps,de_ratio,avg_sentiment_polarity_lag1d,avg_sentiment_neg_lag1d,avg_sentiment_neu_lag1d,avg_sentiment_pos_lag1d,daily_news_count_lag1d
0,2018-11-30 17:50:00,44.60,44.64,44.55,44.63,179494,2018-11-30,0.998000,0.009000,0.925,...,0.216,0.436,0.224,3.194,2.413,NaN,NaN,NaN,NaN,NaN
1,2018-11-30 17:55:00,44.63,44.63,44.52,44.52,218881,2018-11-30,0.998000,0.009000,0.925,...,0.216,0.436,0.224,3.194,2.413,NaN,NaN,NaN,NaN,NaN
2,2018-11-30 18:00:00,44.52,44.55,44.44,44.49,364114,2018-11-30,0.998000,0.009000,0.925,...,0.216,0.436,0.224,3.194,2.413,NaN,NaN,NaN,NaN,NaN
3,2018-11-30 18:05:00,44.49,44.52,44.44,44.46,251652,2018-11-30,0.998000,0.009000,0.925,...,0.216,0.436,0.224,3.194,2.413,NaN,NaN,NaN,NaN,NaN
4,2018-11-30 18:10:00,44.45,44.51,44.44,44.45,200756,2018-11-30,0.998000,0.009000,0.925,...,0.216,0.436,0.224,3.194,2.413,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104023,2024-03-13 22:40:00,171.47,171.65,171.47,171.60,515713,2024-03-13,0.552455,0.027727,0.844,...,NaN,NaN,NaN,NaN,NaN,0.369,0.034615,0.843385,0.122077,13.0
104024,2024-03-13 22:45:00,171.59,171.71,171.50,171.66,566382,2024-03-13,0.552455,0.027727,0.844,...,NaN,NaN,NaN,NaN,NaN,0.369,0.034615,0.843385,0.122077,13.0
104025,2024-03-13 22:50:00,171.65,171.65,171.19,171.29,869695,2024-03-13,0.552455,0.027727,0.844,...,NaN,NaN,NaN,NaN,NaN,0.369,0.034615,0.843385,0.122077,13.0
104026,2024-03-13 22:55:00,171.30,171.30,171.04,171.15,1413942,2024-03-13,0.552455,0.027727,0.844,...,NaN,NaN,NaN,NaN,NaN,0.369,0.034615,0.843385,0.122077,13.0
104027,2024-03-13 23:00:00,171.14,171.16,171.11,171.12,21317,2024-03-13,0.552455,0.027727,0.844,...,NaN,NaN,NaN,NaN,NaN,0.369,0.034615,0.843385,0.122077,13.0

In [115]:
out = Path("/Users/huangyucheng/Desktop/CIS 5450 project/CIS545_Repo/data/processed/merged_data_check2.csv")
df.to_csv(out, index=False)

In [116]:
print(df.columns.tolist())

['datetime', 'open', 'high', 'low', 'close', 'volume', 'merge_date', 'avg_sentiment_polarity', 'avg_sentiment_neg', 'avg_sentiment_neu', 'avg_sentiment_pos', 'daily_news_count', 'CAPEI', 'bm', 'evm', 'pe_op_basic', 'pe_op_dil', 'roa', 'roe', 'npm', 'ps', 'de_ratio', 'avg_sentiment_polarity_lag1d', 'avg_sentiment_neg_lag1d', 'avg_sentiment_neu_lag1d', 'avg_sentiment_pos_lag1d', 'daily_news_count_lag1d']

In [ ]:
sa_cols = ['avg_sentiment_polarity','avg_sentiment_neg','avg_sentiment_neu',
           'avg_sentiment_pos','daily_news_count']

# Rename *_y columns to *_lag1d
df = df.rename(columns={f'{c}_y': f'{c}_lag1d' for c in sa_cols})

# If you no longer need “same-day” news columns, drop the *_x originals
df = df.drop(columns=sa_cols, errors='ignore')

In [118]:
df

,datetime,open,high,low,close,volume,merge_date,CAPEI,bm,evm,...,roa,roe,npm,ps,de_ratio,avg_sentiment_polarity_lag1d,avg_sentiment_neg_lag1d,avg_sentiment_neu_lag1d,avg_sentiment_pos_lag1d,daily_news_count_lag1d
0,2018-11-30 17:50:00,44.60,44.64,44.55,44.63,179494,2018-11-30,17.191,0.1,14.855,...,0.216,0.436,0.224,3.194,2.413,NaN,NaN,NaN,NaN,NaN
1,2018-11-30 17:55:00,44.63,44.63,44.52,44.52,218881,2018-11-30,17.191,0.1,14.855,...,0.216,0.436,0.224,3.194,2.413,NaN,NaN,NaN,NaN,NaN
2,2018-11-30 18:00:00,44.52,44.55,44.44,44.49,364114,2018-11-30,17.191,0.1,14.855,...,0.216,0.436,0.224,3.194,2.413,NaN,NaN,NaN,NaN,NaN
3,2018-11-30 18:05:00,44.49,44.52,44.44,44.46,251652,2018-11-30,17.191,0.1,14.855,...,0.216,0.436,0.224,3.194,2.413,NaN,NaN,NaN,NaN,NaN
4,2018-11-30 18:10:00,44.45,44.51,44.44,44.45,200756,2018-11-30,17.191,0.1,14.855,...,0.216,0.436,0.224,3.194,2.413,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104023,2024-03-13 22:40:00,171.47,171.65,171.47,171.60,515713,2024-03-13,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.369,0.034615,0.843385,0.122077,13.0
104024,2024-03-13 22:45:00,171.59,171.71,171.50,171.66,566382,2024-03-13,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.369,0.034615,0.843385,0.122077,13.0
104025,2024-03-13 22:50:00,171.65,171.65,171.19,171.29,869695,2024-03-13,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.369,0.034615,0.843385,0.122077,13.0
104026,2024-03-13 22:55:00,171.30,171.30,171.04,171.15,1413942,2024-03-13,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.369,0.034615,0.843385,0.122077,13.0
104027,2024-03-13 23:00:00,171.14,171.16,171.11,171.12,21317,2024-03-13,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.369,0.034615,0.843385,0.122077,13.0

In [ ]:
import pandas as pd

# --- Basic: ensure time columns are consistent ---
df['datetime']   = pd.to_datetime(df['datetime'], errors='coerce')
df['merge_date'] = pd.to_datetime(df['merge_date'], errors='coerce').dt.normalize()
df = df.sort_values(['merge_date','datetime'])

# --- Fundamental columns that need to be delayed ---
fa_cols = ['CAPEI','bm','evm','pe_op_basic','pe_op_dil','roa','roe','npm','ps','de_ratio']

# 1) Build a daily-frequency fundamentals table (one row per disclosure date)
fa_day = (
    df[['merge_date'] + fa_cols]
      .drop_duplicates('merge_date')
      .dropna(how='all', subset=fa_cols)
      .sort_values('merge_date')
)

# 2) Fundamentals become visible only 45 days after disclosure
fa_visible = fa_day.copy()
fa_visible['visible_from'] = fa_visible['merge_date'] + pd.Timedelta(days=45)

# 3) Trading-day axis (all calendar trading days derived from the minute-level table)
trade_days = (
    df[['merge_date']]
      .drop_duplicates()
      .sort_values('merge_date')
      .rename(columns={'merge_date':'trade_date'})
)

# 4) As-of merge: for each trading day, get the latest fundamentals that are already visible (<= that day)
fa_asof = pd.merge_asof(
    left = trade_days,
    right= (fa_visible
            .drop(columns=['merge_date'])
            .rename(columns={'visible_from':'trade_date'})
            .sort_values('trade_date')),
    on='trade_date',
    direction='backward'
)

# 4.1 Rename fundamental columns in the as-of table to *_lag45d in advance to avoid conflicts with original columns
lag_map_fa = {c: f'{c}_lag45d' for c in fa_cols}
fa_asof = fa_asof.rename(columns=lag_map_fa)

# 5) Merge back to minute-level data (rename right key back to merge_date)
df = (df.merge(
        fa_asof.rename(columns={'trade_date':'merge_date'}),
        on='merge_date', how='left'
     )
     .sort_values(['merge_date','datetime']))

# 6) Within-day forward-fill: all 5-min bars on the same trading day share the same visible fundamentals
lag_fa_cols = list(lag_map_fa.values())

# If, in extreme cases, some columns are missing (e.g., the entire column is NaN),
# create empty columns first to avoid KeyError
for c in lag_fa_cols:
    if c not in df.columns:
        df[c] = pd.NA

df[lag_fa_cols] = df.groupby('merge_date')[lag_fa_cols].ffill()

# 7) Within-day forward-fill again: all 5-min bars on the same trading day share the same visible fundamentals
lag_fa_cols = list(lag_map_fa.values())
df[lag_fa_cols] = df.groupby('merge_date')[lag_fa_cols].ffill()

In [120]:
df

,datetime,open,high,low,close,volume,merge_date,CAPEI,bm,evm,...,CAPEI_lag45d,bm_lag45d,evm_lag45d,pe_op_basic_lag45d,pe_op_dil_lag45d,roa_lag45d,roe_lag45d,npm_lag45d,ps_lag45d,de_ratio_lag45d
0,2018-11-30 17:50:00,44.60,44.64,44.55,44.63,179494,2018-11-30,17.191,0.1,14.855,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2018-11-30 17:55:00,44.63,44.63,44.52,44.52,218881,2018-11-30,17.191,0.1,14.855,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2018-11-30 18:00:00,44.52,44.55,44.44,44.49,364114,2018-11-30,17.191,0.1,14.855,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2018-11-30 18:05:00,44.49,44.52,44.44,44.46,251652,2018-11-30,17.191,0.1,14.855,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2018-11-30 18:10:00,44.45,44.51,44.44,44.45,200756,2018-11-30,17.191,0.1,14.855,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104023,2024-03-13 22:40:00,171.47,171.65,171.47,171.60,515713,2024-03-13,NaN,NaN,NaN,...,36.549,0.024,22.689,30.836,30.987,0.348,1.698,0.253,7.708,4.673
104024,2024-03-13 22:45:00,171.59,171.71,171.50,171.66,566382,2024-03-13,NaN,NaN,NaN,...,36.549,0.024,22.689,30.836,30.987,0.348,1.698,0.253,7.708,4.673
104025,2024-03-13 22:50:00,171.65,171.65,171.19,171.29,869695,2024-03-13,NaN,NaN,NaN,...,36.549,0.024,22.689,30.836,30.987,0.348,1.698,0.253,7.708,4.673
104026,2024-03-13 22:55:00,171.30,171.30,171.04,171.15,1413942,2024-03-13,NaN,NaN,NaN,...,36.549,0.024,22.689,30.836,30.987,0.348,1.698,0.253,7.708,4.673
104027,2024-03-13 23:00:00,171.14,171.16,171.11,171.12,21317,2024-03-13,NaN,NaN,NaN,...,36.549,0.024,22.689,30.836,30.987,0.348,1.698,0.253,7.708,4.673

In [121]:
out = Path("/Users/huangyucheng/Desktop/CIS 5450 project/CIS545_Repo/data/processed/merged_data_check3.csv")
df.to_csv(out, index=False)